
## Microsoft

### Microsoft Certified Solutions Associate (MCSA): Cloud Platform

#### Requirements

Pass two exams from:			

*	70-532: [Developing Microsoft Azure Solutions](https://www.microsoft.com/en-us/learning/exam-70-532.aspx)	
*	70-533:	[Implementing Microsoft Azure Infrastructure Solutions](https://www.microsoft.com/en-us/learning/exam-70-533.aspx)
*	70-534: [Architecting Microsoft Azure Solutions](https://www.microsoft.com/en-us/learning/exam-70-534.aspx)
*	70-473: [Designing and Implementing Cloud Data Platform Solutions](https://www.microsoft.com/en-us/learning/exam-70-473.aspx)
*	70-475: [Designing and Implementing Big Data Analytics Solutions](https://www.microsoft.com/en-us/learning/exam-70-475.aspx)

More information can be found [here](https://www.microsoft.com/en-us/learning/mcsa-cloud-platform-certification.aspx).

			
### Microsoft Certified Solutions Expert (MCSE): Cloud Platform and Infrastructure

#### Requirements

Earn one of the following MCSA certifications:

*	MCSA: Windows Server 2016
*	MCSA: Cloud Platform
*	MCSA: Linux on Azure
*	MCSA: Windows Server 2012

and pass one of the following exams:

*	532: Developing Azure Solutions
*	533: Implementing Microsoft Azure Infrastructure Solutions
*	534: Architecting Microsoft Azure Solutions
*	473: Designing and Implementing Cloud Data Platform Solutions
*	475: Designing and Implementing Big Data Analytics Solutions
*	744: Securing Windows Server 2016
*	413: Designing and Implementing a Server Infrastructure
*	414: Implementing an Advanced Server Infrastructure
*	246: Monitoring and Operating a Private Cloud
*	247: Configuring and Deploying a Private Cloud

More information can be found [here](https://www.microsoft.com/en-us/learning/mcse-cloud-platform-infrastructure.aspx).
